In [11]:
import pyodbc 
import pandas as pd
import datetime
import numpy as np

In [4]:
'''Connect to post result SQL server'''
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER=dsa-ln-TQA1V;DATABASE=qai;Trusted_Connection=yes')   
cursor = cnxn.cursor()

In [5]:
datetime.datetime.now()

datetime.datetime(2018, 12, 21, 10, 54, 24, 538970)

In [6]:
'''
Broker level estimates
'''

ibdestl_sql="select * from IBDEstL1 where PerType=1 and Period<3 and year(EstDate)>2016 and year(EstDate)<2018"
ibdestl=pd.read_sql(ibdestl_sql,cnxn)

In [61]:
'''
Dataframe with mean, median, count
mean estimate vs previous consensus
mean revision vs previous consensus
mean revision vs previous estimate
same thing applies to year 1 and 2
'''

In [195]:
def key_IBES_metrics(code,date,est_period,revision_period,broker_df,consensus_df):
    '''
    utility function to generate key metrics from broker level data and consensus data
    '''
    broker1=broker_df[(broker_df.Code==code)&(broker_df.Period==1)]
    broker2=broker_df[(broker_df.Code==code)&(broker_df.Period==2)]
    
    consensus1=consensus_df[(consensus_df.Code==code)&(consensus_df.Period==1)]
    consensus2=consensus_df[(consensus_df.Code==code)&(consensus_df.Period==2)]                 
    
    broker1_est=broker1[(broker1.EstDate>=date)&(broker1.EstDate<=date+datetime.timedelta(est_period))]
    broker2_est=broker2[(broker2.EstDate>=date)&(broker2.EstDate<=date+datetime.timedelta(est_period))]
    
    pre_consensus1=consensus1[(consensus1.Code==code)&(consensus1.EstDate<=date)].sort_values("EstDate").iloc[-1]["Mean"]
    post_consensus1=consensus1[(consensus1.Code==code)&(consensus1.EstDate>=date+datetime.timedelta(revision_period))].\
    sort_values("EstDate").iloc[0]["Mean"]
    
    pre_consensus2=consensus2[(consensus2.Code==code)&(consensus2.EstDate<=date)].sort_values("EstDate").iloc[-1]["Mean"]
    post_consensus2=consensus2[(consensus2.Code==code)&(consensus2.EstDate>=date+datetime.timedelta(revision_period))].\
    sort_values("EstDate").iloc[0]["Mean"]
    
    broker1_mean_from_consensus=broker1_est["Value_"].mean()/pre_consensus1-1
    broker1_mean_revision=(broker1_est["Value_"]/pre_consensus1-1).mean()
    broker2_mean_from_consensus=broker2_est["Value_"].mean()/pre_consensus2-1
    broker2_mean_revision=(broker2_est["Value_"]/pre_consensus2-1).mean()

    broker1_median_from_consensus=broker1_est["Value_"].mean()/pre_consensus1-1
    broker1_median_revision=(broker1_est["Value_"]/pre_consensus1-1).median()
    broker2_median_from_consensus=broker2_est["Value_"].mean()/pre_consensus2-1
    broker2_median_revision=(broker2_est["Value_"]/pre_consensus2-1).median()
    
    actual_revision1=post_consensus1/pre_consensus1-1
    actual_revision2=post_consensus2/pre_consensus2-1
    
    count1=broker1_est.shape[0]
    count2=broker2_est.shape[0]
    
    print(pre_consensus1,post_consensus1,broker1_est)
    return broker1_mean_from_consensus,broker1_mean_revision,broker2_mean_from_consensus,broker2_mean_revision,\
           broker1_median_from_consensus,broker1_median_revision,broker2_median_from_consensus,broker2_median_revision,\
           actual_revision1,actual_revision2,count1,count2

In [196]:
key_IBES_metrics(target[0],target[1],2,20,ibdestl,ibesusdlyest)

6.98227262496948 7.00099992752075        Code  Measure  Broker  Analyst  PerType  Period    EstDate    PerDate  \
15039   919        8     238   117325        1       1 2017-02-08 2017-12-31
15062   919        8    2301    83036        1       1 2017-02-08 2017-12-31
15807   919        8    3322   185662        1       1 2017-02-07 2017-12-31
15821   919        8   50531   640084        1       1 2017-02-07 2017-12-31
15825   919        8   51020   619416        1       1 2017-02-08 2017-12-31
15836   919        8   51382   614735        1       1 2017-02-07 2017-12-31
15844   919        8   51534   618773        1       1 2017-02-07 2017-12-31
15856   919        8   52135   576405        1       1 2017-02-08 2017-12-31

      Currency_ PDFlag  Value_    RevDate IsoCurrency
15039                D   6.950 2017-02-08        None
15062                D   6.940 2017-02-15        None
15807                D   6.890 2017-02-07        None
15821                D   6.995 2017-02-07        None
15825                D   7.250 2017-02-08        None
15836                D   7.050 2017-03-06        None
15844                D   7.010 2017-05-04        None
15856                D   6.690 2017-02-13        None

(-0.0014891462318868953,
 -0.001489146231886826,
 0.008869163956453763,
 0.008869163956453995,
 -0.0014891462318868953,
 -0.0013996338290389598,
 0.008869163956453763,
 0.01490513331345844,
 0.0026821213603576144,
 0.01219507782589635,
 8,
 11)

In [114]:
target

(2, Timestamp('2017-01-31 00:00:00'), Timestamp('2016-12-31 00:00:00'))

In [120]:
datetime.timedelta(3)

datetime.timedelta(3)

In [185]:
ibdestl[(ibdestl.Code==target[0])&(ibdestl.EstDate>=target[1])&(ibdestl.EstDate<=target[1]+datetime.timedelta(2))]

,Code,Measure,Broker,Analyst,PerType,Period,EstDate,PerDate,Currency_,PDFlag,Value_,RevDate,IsoCurrency
3791,330,8,100,110494,1,1,2017-02-01,2017-12-31,,D,3.2225,2017-03-27,None
3796,330,8,100,110494,1,2,2017-02-01,2018-12-31,,D,3.3010,2017-03-27,None
3817,330,8,228,45242,1,1,2017-02-02,2017-12-31,,D,3.1750,2017-02-02,None
3820,330,8,228,45242,1,2,2017-02-02,2018-12-31,,D,3.3250,2017-02-02,None
3824,330,8,238,71713,1,1,2017-02-01,2017-12-31,,D,3.2200,2017-02-01,None
3828,330,8,238,71713,1,2,2017-02-01,2018-12-31,,D,3.3250,2017-02-01,None
3832,330,8,282,129977,1,1,2017-02-01,2017-12-31,,D,3.1600,2017-04-13,None
3857,330,8,3374,71396,1,1,2017-01-31,2017-12-31,,D,3.1600,2017-03-31,None
3864,330,8,3374,71396,1,2,2017-01-31,2018-12-31,,D,3.3200,2017-03-31,None
3871,330,8,50659,611531,1,1,2017-02-01,2017-12-31,,D,3.1850,2017-04-13,None
3876,330,8,50659,611531,1,2,2017-02-01,2018-12-31,,D,3.2700,2017-04-13,None
3970,330,8,51243,523227,1,1,2017-02-01,2017-12-31,,D,3.1700,2017-02-27,None
3974,330,8,51243,523227,1,2,2017-02-01,2018-12-31,,D,3.3350,2017-02-27,None
3994,330,8,51382,511562,1,2,2017-02-01,2018-12-31,,D,3.3750,2017-02-01,None
4000,330,8,51534,588610,1,1,2017-02-01,2017-12-31,,D,3.1750,2017-04-06,None
4004,330,8,51534,588610,1,2,2017-01-31,2018-12-31,,D,3.4000,2017-01-31,None
4005,330,8,51534,588610,1,2,2017-02-01,2018-12-31,,D,3.3750,2017-04-06,None
4011,330,8,51595,614516,1,1,2017-02-01,2017-12-31,,D,3.2000,2017-03-20,None
4019,330,8,51595,614516,1,2,2017-02-01,2018-12-31,,D,3.4250,2017-03-20,None
4025,330,8,52024,584124,1,1,2017-02-01,2017-12-31,,D,3.2000,2017-02-23,None
4032,330,8,52024,584124,1,2,2017-02-01,2018-12-31,,D,3.4000,2017-07-27,None
4047,330,8,60902,606345,1,1,2017-02-01,2017-12-31,,D,3.2500,2017-04-16,None

In [180]:
'''
Pre value
'''
ibesusdlyest[(ibesusdlyest.Code==target[0])&(ibesusdlyest.EstDate<=target[1])&(ibesusdlyest.Period==1)].\
sort_values("EstDate").iloc[-1]["Mean"]

6.44168758392334

In [181]:
'''
Post value
'''
ibesusdlyest[(ibesusdlyest.Code==target[0])&(ibesusdlyest.EstDate>=target[1]+datetime.timedelta(20))&(ibesusdlyest.Period==1)].\
sort_values("EstDate").iloc[0]["Mean"]

6.38970565795898

In [187]:
ibesusdlyest[ibesusdlyest.Code==target[0]]

,Code,Measure,EstDate,PerDate,Period,PerType,NumEst,Median,Mean,StdDev,High,Low,PdFlag,Currency_
1947,330,8,2017-02-17,2018-12-31,2,1,17,6.7000,6.706000,0.087175,6.850,6.540,D,USD
2010,330,8,2017-04-18,2017-12-31,1,1,17,6.4400,6.426764,0.058495,6.510,6.320,D,USD
2011,330,8,2017-04-20,2017-12-31,1,1,17,6.4450,6.436765,0.051019,6.510,6.320,D,USD
2012,330,8,2017-04-24,2017-12-31,1,1,17,6.4500,6.438824,0.052068,6.510,6.320,D,USD
2023,330,8,2017-04-03,2017-12-31,1,1,17,6.4000,6.406177,0.060610,6.510,6.320,D,USD
2024,330,8,2017-04-06,2017-12-31,1,1,17,6.4000,6.412059,0.064688,6.510,6.320,D,USD
2025,330,8,2017-04-13,2017-12-31,1,1,17,6.4000,6.417941,0.063222,6.510,6.320,D,USD
2026,330,8,2017-07-25,2017-12-31,1,1,16,6.5050,6.506875,0.054002,6.600,6.400,D,USD
2027,330,8,2017-04-03,2018-12-31,2,1,17,6.7000,6.716000,0.092382,6.850,6.540,D,USD
2028,330,8,2017-04-06,2018-12-31,2,1,17,6.7000,6.721882,0.103912,6.950,6.540,D,USD
2029,330,8,2017-04-13,2018-12-31,2,1,17,6.7000,6.727765,0.108339,6.950,6.540,D,USD
2030,330,8,2017-07-25,2018-12-31,2,1,16,6.7500,6.755688,0.105667,6.900,6.501,D,USD
2072,330,8,2017-04-28,2017-12-31,1,1,17,6.5000,6.476823,0.075971,6.600,6.320,D,USD
2073,330,8,2017-05-01,2017-12-31,1,1,17,6.5260,6.497412,0.087985,6.650,6.320,D,USD
2074,330,8,2017-05-02,2017-12-31,1,1,17,6.5260,6.508000,0.058890,6.600,6.400,D,USD
2075,330,8,2017-08-14,2017-12-31,1,1,16,6.7000,6.687000,0.069933,6.850,6.570,D,USD
2076,330,8,2017-04-18,2018-12-31,2,1,17,6.7000,6.727765,0.108339,6.950,6.540,D,USD
2077,330,8,2017-04-19,2018-12-31,2,1,17,6.7000,6.730706,0.112465,6.950,6.540,D,USD
2078,330,8,2017-04-20,2018-12-31,2,1,17,6.7500,6.741882,0.112329,6.950,6.540,D,USD
2079,330,8,2017-04-24,2018-12-31,2,1,17,6.7500,6.744529,0.109316,6.950,6.540,D,USD
2080,330,8,2017-04-28,2018-12-31,2,1,17,6.7500,6.757471,0.096424,6.950,6.610,D,USD
2081,330,8,2017-05-01,2018-12-31,2,1,17,6.7500,6.762177,0.092732,6.900,6.610,D,USD
2082,330,8,2017-05-02,2018-12-31,2,1,17,6.7500,6.769235,0.087828,6.900,6.610,D,USD
2083,330,8,2017-08-14,2018-12-31,2,1,16,6.8380,6.826562,0.123728,7.050,6.599,D,USD
2132,330,8,2017-07-11,2017-12-31,1,1,16,6.5280,6.521000,0.044362,6.600,6.450,D,USD
2133,330,8,2017-07-12,2017-12-31,1,1,16,6.5230,6.519125,0.043684,6.600,6.450,D,USD
2134,330,8,2017-07-17,2017-12-31,1,1,16,6.5150,6.515000,0.046043,6.600,6.450,D,USD
2135,330,8,2017-11-01,2017-12-31,1,1,14,6.7575,6.753214,0.047459,6.850,6.670,D,USD
2136,330,8,2017-11-06,2017-12-31,1,1,15,6.7550,6.753000,0.045740,6.850,6.670,D,USD
2137,330,8,2017-07-12,2018-12-31,2,1,16,6.7500,6.772937,0.086445,6.900,6.610,D,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,330,8,2017-02-02,2018-12-31,2,1,15,6.6700,6.710134,0.102874,6.900,6.540,D,USD
2439,330,8,2017-02-03,2018-12-31,2,1,16,6.6850,6.709500,0.099418,6.900,6.540,D,USD
2440,330,8,2017-02-13,2018-12-31,2,1,16,6.6850,6.703250,0.089269,6.850,6.540,D,USD
2441,330,8,2017-08-01,2018-12-31,2,1,16,6.8150,6.820562,0.125043,7.050,6.599,D,USD
2729,330,8,2017-03-02,2017-12-31,1,1,17,6.3900,6.389706,0.055466,6.500,6.320,D,USD
3477,330,8,2017-05-11,2017-12-31,1,1,17,6.5260,6.510941,0.054222,6.600,6.400,D,USD
3478,330,8,2017-05-15,2017-12-31,1,1,17,6.5260,6.516823,0.046277,6.600,6.450,D,USD
3479,330,8,2017-10-30,2017-12-31,1,1,15,6.7500,6.742667,0.054178,6.850,6.650,D,USD
3480,330,8,2017-05-15,2018-12-31,2,1,17,6.7500,6.775118,0.082532,6.900,6.610,D,USD
3481,330,8,2017-10-30,2018-12-31,2,1,15,6.8000,6.810534,0.086164,7.000,6.660,D,USD
3482,330,8,2017-11-07,2018-12-31,2,1,15,6.8000,6.812400,0.085444,7.000,6.660,D,USD
235949,330,8,2017-07-28,2017-12-31,1,1,16,6.5600,6.586875,0.115512,6.850,6.450,D,USD
235950,330,8,2017-07-31,2017-12-31,1,1,16,6.6350,6.631875,0.121612,6.850,6.450,D,USD
235951,330,8,2017-07-28,2018-12-31,2,1,16,6.7500,6.780687,0.140933,7.050,6.501,D,USD
235952,330,8,2017-07-31,2018-12-31,2,1,16,6.7750,6.808187,0.138859,7.050,6.501,D,USD
236153,330,8,2017-10-19,2017-12-31,1,1,15,6.7000,6.694000,0.061621,6.800,6.570,D,USD
236154,330,8,2017-10-23,2017-12-31,1,1,15,6.7000,6.696000,0.059857,6.800,6.570,D,USD
236155,330,8,2017-10-26,2017-12-31,1,1,15,6.7500,6.741333,0.053568,6.850,6.650,D,USD
236156,330,8,2017-10-20,2018-12-31,2,1,15,6.8000,6.801867,0.071440,6.950,6.700,D,USD
236157,330,8,2017-10-23,2018-12-31,2,1,15,6.8000,6.802533,0.070462,6.950,6.700,D,USD
236158,330,8,2017-10-26,2018-12-31,2,1,15,6.8000,6.813867,0.084608,7.000,6.660,D,USD
236516,330,8,2017-09-14,2017-12-31,1,1,15,6.7000,6.686666,0.072375,6.850,6.570,D,USD
236517,330,8,2017-12-04,2017-12-31,1,1,15,6.7500,6.757000,0.041136,6.850,6.670,D,USD
236518,330,8,2017-09-14,2018-12-31,2,1,15,6.8460,6.841733,0.111609,7.050,6.700,D,USD
236916,330,8,2017-11-27,2018-12-31,2,1,15,6.8000,6.808400,0.088583,7.000,6.660,D,USD
237029,330,8,2017-12-18,2017-12-31,1,1,15,6.7550,6.757333,0.041095,6.850,6.670,D,USD
237030,330,8,2017-12-18,2018-12-31,2,1,15,6.8000,6.816133,0.077657,7.000,6.730,D,USD
237031,330,8,2017-12-22,2018-12-31,2,1,15,6.8000,6.967333,0.361853,7.750,6.730,D,USD
237219,330,8,2017-12-21,2018-12-31,2,1,15,6.8000,6.907333,0.290360,7.654,6.730,D,USD
245298,330,8,2017-12-01,2018-12-31,2,1,15,6.8000,6.819733,0.080345,7.000,6.730,D,USD

In [194]:
ibesusdlyest[(ibesusdlyest.Code==target[0])&(ibesusdlyest.EstDate>=target[1]+datetime.timedelta(20))&(ibesusdlyest.Period==1)].\
sort_values("EstDate")

,Code,Measure,EstDate,PerDate,Period,PerType,NumEst,Median,Mean,StdDev,High,Low,PdFlag,Currency_
7436,919,8,2017-02-28,2017-12-31,1,1,10,6.980,7.001000,0.125738,7.25,6.840,D,USD
7440,919,8,2017-03-01,2017-12-31,1,1,10,6.980,7.026000,0.189455,7.50,6.840,D,USD
7706,919,8,2017-03-21,2017-12-31,1,1,10,6.980,7.029000,0.189763,7.50,6.840,D,USD
7707,919,8,2017-03-24,2017-12-31,1,1,10,7.030,7.040000,0.187202,7.50,6.840,D,USD
7708,919,8,2017-04-10,2017-12-31,1,1,10,7.030,7.035000,0.173734,7.45,6.840,D,USD
7638,919,8,2017-05-04,2017-12-31,1,1,10,7.065,7.080000,0.184451,7.45,6.840,D,USD
7565,919,8,2017-05-05,2017-12-31,1,1,10,7.115,7.108000,0.181647,7.40,6.700,D,USD
7324,919,8,2017-06-23,2017-12-31,1,1,10,7.115,7.121000,0.151324,7.40,6.830,D,USD
7787,919,8,2017-07-18,2017-12-31,1,1,10,7.115,7.125000,0.154434,7.40,6.830,D,USD
7788,919,8,2017-07-19,2017-12-31,1,1,10,7.140,7.138000,0.162056,7.40,6.830,D,USD
7709,919,8,2017-07-26,2017-12-31,1,1,10,7.140,7.149000,0.170974,7.40,6.830,D,USD
8241,919,8,2017-08-03,2017-12-31,1,1,10,7.240,7.183000,0.174423,7.40,6.830,D,USD
8242,919,8,2017-08-04,2017-12-31,1,1,10,7.300,7.249000,0.176412,7.45,6.830,D,USD
245808,919,8,2017-08-07,2017-12-31,1,1,10,7.300,7.270000,0.163435,7.45,6.830,D,USD
7639,919,8,2017-08-10,2017-12-31,1,1,9,7.300,7.318889,0.056224,7.45,7.260,D,USD
7325,919,8,2017-10-05,2017-12-31,1,1,9,7.300,7.321111,0.057106,7.45,7.260,D,USD
7884,919,8,2017-10-13,2017-12-31,1,1,9,7.300,7.325555,0.057687,7.45,7.260,D,USD
237882,919,8,2017-10-24,2017-12-31,1,1,9,7.350,7.331111,0.057325,7.45,7.260,D,USD
7566,919,8,2017-10-31,2017-12-31,1,1,9,7.350,7.332222,0.057831,7.45,7.260,D,USD
7789,919,8,2017-11-02,2017-12-31,1,1,10,7.325,7.282000,0.167915,7.45,6.830,D,USD
7790,919,8,2017-11-03,2017-12-31,1,1,9,7.350,7.348000,0.026758,7.38,7.292,D,USD
238771,919,8,2017-12-07,2017-12-31,1,1,10,7.350,7.343200,0.029442,7.38,7.292,D,USD

In [7]:
'''
Daily consensus data
'''

ibesusdlyest_sql=\
"select * from IBESUSDLYEST where PerType=1 and Period<3 and Measure=8 and year(EstDate)>2016 and year(EstDate)<2018"
ibesusdlyest=pd.read_sql(ibesusdlyest_sql,cnxn)

In [37]:
'''
Actual reporting data
'''

ibdactl_sql="select * from IBDActL1 where PerType='Q' and year(RptDate)>2016 and year(RptDate)<2018"
ibdactl=pd.read_sql(ibdactl_sql,cnxn)

In [88]:
len(alist)

21264

In [94]:
alist=list(zip(ibdactl.Code,ibdactl.RptDate,ibdactl.PerDate))

In [191]:
target=alist[500]

In [192]:
target

(919, Timestamp('2017-02-07 00:00:00'), Timestamp('2016-12-31 00:00:00'))

In [193]:
ibdestl[(ibdestl.Code==target[0])&(ibdestl.EstDate>=target[1])&(ibdestl.EstDate<=target[1]+datetime.timedelta(2))]

,Code,Measure,Broker,Analyst,PerType,Period,EstDate,PerDate,Currency_,PDFlag,Value_,RevDate,IsoCurrency
15033,919,8,228,187538,1,2,2017-02-07,2018-12-31,,D,7.350,2017-05-04,None
15039,919,8,238,117325,1,1,2017-02-08,2017-12-31,,D,6.950,2017-02-08,None
15043,919,8,238,117325,1,2,2017-02-08,2018-12-31,,D,7.550,2017-02-08,None
15053,919,8,260,76873,1,2,2017-02-07,2018-12-31,,D,7.490,2017-03-19,None
15062,919,8,2301,83036,1,1,2017-02-08,2017-12-31,,D,6.940,2017-02-15,None
15799,919,8,2301,83036,1,2,2017-02-08,2018-12-31,,D,7.410,2017-02-15,None
15807,919,8,3322,185662,1,1,2017-02-07,2017-12-31,,D,6.890,2017-02-07,None
15811,919,8,3322,185662,1,2,2017-02-07,2018-12-31,,D,7.200,2017-02-07,None
15817,919,8,50203,619739,1,2,2017-02-08,2018-12-31,,D,7.750,2017-05-04,None
15821,919,8,50531,640084,1,1,2017-02-07,2017-12-31,,D,6.995,2017-02-07,None
15823,919,8,50531,640084,1,2,2017-02-07,2018-12-31,,D,7.400,2017-02-07,None
15825,919,8,51020,619416,1,1,2017-02-08,2017-12-31,,D,7.250,2017-02-08,None
15831,919,8,51020,619416,1,2,2017-02-08,2018-12-31,,D,7.550,2017-02-08,None
15836,919,8,51382,614735,1,1,2017-02-07,2017-12-31,,D,7.050,2017-03-06,None
15840,919,8,51382,614735,1,2,2017-02-07,2018-12-31,,D,7.700,2017-03-06,None
15844,919,8,51534,618773,1,1,2017-02-07,2017-12-31,,D,7.010,2017-05-04,None
15850,919,8,51534,618773,1,2,2017-02-07,2018-12-31,,D,7.630,2017-05-04,None
15856,919,8,52135,576405,1,1,2017-02-08,2017-12-31,,D,6.690,2017-02-13,None
15861,919,8,52135,576405,1,2,2017-02-08,2018-12-31,,D,6.870,2017-02-13,None

In [99]:
sum_df=pd.DataFrame(index=pd.MultiIndex.from_tuples(alist))

In [40]:
ibesinfo3_sql="select * from IBESInfo3"
ibesinfo3=pd.read_sql(ibesinfo3_sql,cnxn)

In [186]:
ibesinfo3[ibesinfo3["Code"]==330]

,ITicker,Cusip,STicker,Name,Country,Currency_,OneTenth,SecType,ExchCtry,Exchange,Code
1209,AFL,00105510,AFL,AFLAC INC,NA,USD,0,S,NA,A,330